FILE(MAKE_DIRECTORY "/home/filip/catkin_ws/devel/share/labust_mission/graphs" )
FILE(GLOB_RECURSE FOR_DEL /home/filip/catkin_ws/devel/share/labust_mission/graphs/* )
#message("delete files from /home/filip/catkin_ws/devel/share/labust_mission/graphs/ : ${FOR_DEL}")
if( FOR_DEL )
	FILE(REMOVE ${FOR_DEL})
endif()
execute_process(COMMAND /home/filip/catkin_ws/devel/lib/decision_making_parser/decision_making_parser -pe -xml -dot -src "/home/filip/catkin_ws/src/labust-ros-pkg/labust_mission" -dst "/home/filip/catkin_ws/devel/share/labust_mission/graphs" -f "/home/filip/catkin_ws/src/labust-ros-pkg/labust_mission/src/mission_exec.cpp:" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/filip/catkin_ws/devel/share/labust_mission/graphs/ /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.scxml /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.btxml  /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.taoxml)
message("   -- Created XML files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.scxml /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.btxml /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.taoxml)
execute_process(COMMAND "python" /home/filip/catkin_ws/devel/lib/decision_making_parser/decision_making_xml_parser.py -i "/home/filip/catkin_ws/src/labust-ros-pkg/labust_mission" "/home/filip/catkin_ws/devel/share/labust_mission/graphs" "${CREATED_FILES_ABS}" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/filip/catkin_ws/devel/share/labust_mission/graphs/ /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.dot /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.xot)
message("   -- Created DOT files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.dot)
foreach( f ${CREATED_FILES_ABS} )
	execute_process(COMMAND "dot" -q1 -Tgif -o${f}.gif  ${f} RESULT_VARIABLE rv)
endforeach()
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/filip/catkin_ws/devel/share/labust_mission/graphs/ /home/filip/catkin_ws/devel/share/labust_mission/graphs/*.gif)
message("   -- Created GIF files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
