function csv = prep_log(name)
  data = csv2struct(name);
  csv = [data.tauAch.wrench.force.x', ...
      data.tauAch.wrench.force.y', ...
      data.tauAch.wrench.torque.z', ...
      data.meas.position.north', ...
      data.meas.position.east', ...
      data.meas.orientation.yaw', ...
      data.imu_info.gyro_z'];
  
  file = fopen(strcat(name,'_prep'),'wt');
  fprintf(file,'%.8f %.8f %.8f %.8f %.8f %.8f %.8f\n',csv');
  fclose(file);
end