function [sonar, lib] = loadBvtSdk(type, fileName)
lib = 'libbvtsdk';

if libisloaded(lib) == 1; unloadlibrary(lib); end
    
loadlibrary(['/usr/local/lib/' lib '.so'] , ...
    '/usr/local/include/bvt_sdk.h' , ...
            'addheader','bvt_c/bvt_colormapper.h',...
            'addheader','bvt_c/bvt_error.h',...
            'addheader','bvt_c/bvt_head.h',...
            'addheader','bvt_c/bvt_logger.h',...
            'addheader','bvt_c/bvt_magimage.h',...
            'addheader','bvt_c/bvt_ping.h',...
            'addheader','bvt_c/bvt_retval.h',...
            'addheader','bvt_c/bvt_colorimage.h',...
            'addheader','bvt_c/bvt_sonar.h',...
    'includepath' , '/usr/local/include/');

sonar = calllib('libbvtsdk', 'BVTSonar_Create');
calllib('libbvtsdk', 'BVTSonar_Open', sonar, type, fileName);

end